### ISSUE TITLE
Jumpcut won't paste

### ISSUE THREAD

**Issue by jimtparr** [snark/jumpcut#31] opened 2019-10-19 20:05 UTC
Clicking on something in Jumpcut doesn't paste it.  Makes Jumpcut essentially useless to me.  macOS10.15, supplementary version

**Comment by bunk3m** [comment] 2019-10-20 18:34
I noticed this change in behaviour since the update but thought I was 
doing something different.

I think in 0.63, you could click on the item in the dropdown list and it 
would paste or load into the buffer so you could use ctrl+v.

I'm on 10.14.6.

B.

**Comment by jimtparr** [comment] 2019-10-20 19:44
B.-

By golly, it works!  So I can continue to use Jumpcut after all.  Thank you so much for the tip; I would never have guessed that.  I’ve been trying out Keyboard Maestro's macro for clipboard history, which has all the functionality and maybe more, but is awkward to access, trying without success to make it as handy as Jumpcut.

                              —Jim

A society that presumes a norm of violence and celebrates aggression, whether in the subway, on the football field, or in the conduct of its business, cannot help making celebrities of the people who would destroy it. -Lewis H. Lapham

On Oct 20, 2019, at 1:34 PM, Bunk3m <notifications@github.com<mailto:notifications@github.com>> wrote:

[This message came from an external source. If suspicious, report to abuse@ilstu.edu<mailto:abuse@ilstu.edu>]
I noticed this change in behaviour since the update but thought I was
doing something different.

I think in 0.63, you could click on the item in the dropdown list and it
would paste or load into the buffer so you could use ctrl+v.

I'm on 10.14.6.

B.

**Comment by bunk3m** [comment] 2019-10-20 21:13
Jim, I think this is still a change in behaviour from 0.63.

If I remember correctly, double clicking on the item in the drop down would paste, not just load the clipboard.

Am I wrong here @snark ?

**Comment by jimtparr** [comment] 2019-10-21 03:51
I tried double clicking and couldn’t get it to work.  Click then paste seems to work reliably, and that’s pretty good.

                              —Jim

It is far better to grasp the universe as it really is than to persist in delusion, however satisfying or reassuring.   ~Sagan

On Oct 20, 2019, at 4:13 PM, Bunk3m <notifications@github.com<mailto:notifications@github.com>> wrote:

[This message came from an external source. If suspicious, report to abuse@ilstu.edu<mailto:abuse@ilstu.edu>]

Jim, I think this is still a change in behaviour from 0.63.

If I remember correctly, double clicking on the item in the drop down would paste, not just load the clipboard.

Am I wrong here @snark<https://github.com/snark> ?

**Comment by snark** [comment] 2019-10-22 12:26
There's a checkbox in the general preferences, "Clipping selection pastes". When that's checked, Jumpcut pastes on selection from the menu bar; when it's unchecked, it moves the selection onto the pasteboard to be pasted manually.

**Comment by snark** [comment] 2019-10-22 12:27
I don't remember having a double-click feature available in 0.63--possibly that's one of the behaviors added by Flycut, which was a fork of Jumpcut?

**Comment by bunk3m** [comment] 2019-10-23 02:01
@snark thank you.  The "Clipping selection pastes" "selected" isn't pasting automatically when you click on the line in the menu bar dropdown.  But the click to put into the paste buffer does work.

I have only used Jumpcut.  I'm pretty sure the double-click was in 0.63 as when I started trying 0.7.x I was trying to double click on items in the drop down and was confused that it didn't do anything.

**Comment by dylantack** [comment] 2019-12-18 18:18
I had this problem too - I was able to fix it by removing Jumpcut from System Preferences -> Security & Privacy-> Privacy -> Accessibility. Then re-add it, and re-launch jumpcut.

**Comment by snark** [comment] 2020-02-23 17:23
Closing this one out; I believe this is essentially a duplicate of #17, where the Accessibility behavior doesn't work on upgrades until it's manually removed and re-added.

**Closed by snark** 2020-02-23 17:23 UTC

**Comment by jimtparr** [comment] 2020-02-23 21:03
Thank you.  I followed the link and it worked.  I had got used to clicking on a Jumpcut entry to put it on the clipboard again and then pasting, but now that pastes it directly, as Jumpcut originally did.  That will save me a tiny amount of time, but thousands of times.

                              —Jim

"It is never too late to be who you might have been"  --George Eliot
On Feb 23, 2020, at 11:23 AM, Steve Cook <notifications@github.com<mailto:notifications@github.com>> wrote:

[This message came from an external source. If suspicious, report to abuse@ilstu.edu<mailto:abuse@ilstu.edu>]

Closing this one out; I believe this is essentially a duplicate of #17<https://github.com/snark/jumpcut/issues/17>, where the Accessibility behavior doesn't work on upgrades until it's manually removed and re-added.

**Comment by brianashe** [comment] 2023-12-22 20:57
Greetings from the future! I had this issue in 12/2023 with Jumpcut 0.82 after updating an old laptop to Monterey. I quit Jumpcut, removed it from Security -> Accessibility, launched Jumpcut, let it take me to Security -> Accessibility, re-enabled it there, and it worked. (I might have had to quit and relaunch Junpcut one more time after that, I forget.)

Thanks all!
