### ISSUE TITLE
Pasting via the bezel cannot be cancelled via the keyboard (Escape key)

### ISSUE THREAD

**Issue by sometimesfood** [snark/jumpcut#77] opened 2022-05-07 19:56 UTC
Thanks for Jumpcut, I have been using Jumpcut for over a decade now and it's one of those rare tools that just works and gets out of the way. I really appreciate your work!

In previous versions of Jumpcut, when I inadvertently brought up the bezel or could not find the clipboard item I was looking for, I was able to cancel pasting by pressing the Escape key.

With Jumpcut 0.81, pressing Escape no longer closes the bezel. The only way to close the bezel without pasting the currently selected item seems to be to use the mouse and click outside the bezel. (I don't know if this was an intentional change or a regression from the Swift rewrite.)

Being able to cancel a paste via the keyboard was a great feature. Could you please restore the old behaviour, where pressing the Escape key closed the bezel without pasting?

**Comment by snark** [comment] 2022-05-07 20:27
@sometimesfood Thanks for the bug report--this is something I've noticed as well, that seems specifically caused by "Control-Escape". In particular, using the default hotkey of control-option-V (my personal preference), pressing escape while holding control-option doesn't work; releasing control and pressing escape while holding option does. It's an annoyance to me, as well; my guess is that something else wants the key combo, but I haven't tracked it down yet. I've got it on my list of issues to look at, but it's good to have an issue filed to capture the problem.

If you can confirm that you get the same behavior--a failure to dismiss the bezel *only* if control is depressed--I'd appreciate it. (And thanks for using Jumpcut.)

**Comment by sometimesfood** [comment] 2022-05-07 20:36
Wow, thanks for the extremely fast response!

> It's an annoyance to me, as well; my guess is that something else wants the key combo, but I haven't tracked it down yet.

The behaviour described above seems to have been introduced in Jumpcut 0.80. If I start an old copy of Jumpcut 0.75, everything works just as expected.

> If you can confirm that you get the same behavior--a failure to dismiss the bezel only if control is depressed--I'd appreciate it.

Yes, I hadn't noticed that before, but that's exactly the same behaviour that I get. Thanks, that's a nice workaround to avoid going for my mouse/touchpad! :)

**Comment by snark** [comment] 2022-05-08 13:59
A fix for this will be released in 0.82.

**Comment by sometimesfood** [comment] 2022-05-08 15:44
That's great news, thank you for your great work!

**Comment by capndesign** [comment] 2022-05-10 13:26
Hi @snark! Just here to say I appreciate you. This was my one and only bug report from .8x. Thanks for being so responsive!

**Comment by snark** [comment] 2022-05-13 13:06
@capndesign Thanks, Matty! <3

**Comment by jallen92** [comment] 2022-05-13 15:56
So glad to see this bug not only reported already but also fixed! This was my only gripe with the new changes. Thanks @snark for being scary fast with the fix and for all the work you do on Jumpcut 🙏 ! This is one of my few must have apps for any new macOS install.

**Comment by snark** [comment] 2022-05-25 11:45
Now released in 0.82, with Sparkle updates arriving shortly. Thanks for your patience, everyone!

**Closed by snark** 2022-05-25 11:45 UTC
Labels: bug, next-version
