### ISSUE TITLE
Bezel is locked to Space where Jumpcut was opened

### ISSUE THREAD

**Issue by g000m** [snark/jumpcut#67] opened 2022-04-29 17:21 UTC
My standard workflow involves 3 MacOS Spaces on my right monitor. Since updating to 0.80, I am seeing that the bezel is locked to the space I was in when I opened Jumpcut. The effect is similar to switching to an application window that is in another space. I hit the bezel shortcut, and my screen slides to the space where Jumpcut is running. Relaunching Jumpcut in a different space will lock it there.

I appreciate all of your work on this!

**Comment by snark** [comment] 2022-04-30 00:39
Thanks; with the change to Swift, there have probably been some regressions in more obscure areas of the code. I may reach out to you to confirm a fix!

**Comment by caewok** [comment] 2022-04-30 01:46
Yes, I am seeing the same thing running 12.3.1 with Spaces on my laptop.

**Comment by snark** [comment] 2022-04-30 02:27
@caewok @g000m Thanks so much for the bug report; this was an easy change to make, and will be included in a a bug fix release in the next week or two.

**Comment by caewok** [comment] 2022-05-01 16:14
Great, thanks!

**Comment by disbelief** [comment] 2022-05-02 14:40
Came to create an issue about this as well. Thanks for resolving it so quickly @snark — looking forward to the new release!

**Comment by thejohnha** [comment] 2022-05-03 16:05
I just wanted to thank you Steve @snark for Jumpcut. Your passion project has been so useful for all of us. Very grateful 🙏

**Comment by mijogu** [comment] 2022-05-05 16:48
Ditto, I want to thank @snark as well. Been using Jumpcut for years. It's absolutely inherent to my daily workflow. Whenever I'm pairing with someone and they notice it, I insist them are missing out.

**Comment by snark** [comment] 2022-05-06 22:26
I'll leave this open for a day or two in case anyone is continuing to have issues, but I can confirm that the issue is resolved for me in 0.81, running Big Sur. Thanks for the bug report!

**Comment by mijogu** [comment] 2022-05-09 17:51
@snark you're awesome. thank you

**Comment by caewok** [comment] 2022-05-09 23:09
Yes, thanks so much! This may be my most used app!

**Comment by snark** [comment] 2022-05-13 13:16
@caewok @mijogu @disbelief @g000m No further reports of issues, so I think this is fixed. Please feel free to reopen the ticket if there remain issues with Spaces/multiple desktops under 0.81!

**Closed by snark** 2022-05-13 13:16 UTC
Labels: bug, next-version
