### ISSUE TITLE
Custom Hotkey Prevents Cycling Through Selections

### ISSUE THREAD

**Issue by DenVog** [snark/jumpcut#47] opened 2020-07-08 23:09 UTC
If I use the default hotkey of Command + Option + V, then release V, it allows me to use the arrow keys to cycle through the history to select an item, and by releasing Command + Option it pastes.

if I change the master hotkey to something like Control + Option + V, it will only display the last selection. No ability to cycle through with the arrows. Releasing Control + Option pastes that selection.

I started using Magnet and its default Control + Option (no use of V), and I was hoping to have a single hotkey combination for both.

Love Jumpcut. Been using it for years. Thanks for keeping it working with the new OS releases.

**Comment by snark** [comment] 2020-09-07 23:14
@DenVog I can't reproduce this; when I switch the hotkey to control-option-V, the standard navigation (holding control-option, V and shift-V, as well as the arrows) continue to function. Is it possible Magnet is also listening for control-option-arrow? If multiple applications register a global hotkey, things can get weird. If that's the case, Jumpcut will remain active as long as *any* modifier key is depressed; that is, you could activate with control-option-V, release option and V, and navigate holding control and using the arrows.

**Comment by Daniding** [comment] 2021-08-30 16:56
Hi, 
new to Mac, was looking for replacement for ditto (Win), and found your wonderful tool. Like @DenVog I tried changing the hot key to something that I can invoke easily in one hand (I changed it to control+§) and the same thing happen to me, I can no longer cycle using the arrow keys. (I can still cycle using the new hot key, but really miss the arrows option).

Many thanks for this great creation! :)

**Comment by snark** [comment] 2022-05-04 12:40
@Daniding @DenVog If either of you is still using Jumpcut under the new release, 0.80, can you tell me if this problem is still occurring? There's an additional bug fix coming for non-QWERTY keyboards in 0.81, but Jumpcut now uses the Sauce abstraction library for keyboard lookup, so this problem may now be resolved.

**Comment by snark** [comment] 2022-06-02 12:59
I'm going to close this one based on the work done in 0.81 specifically addressing French keyboards, but @Daniding or @DenVog should feel free to reopen it if they're still having problems.

**Closed by snark** 2022-06-02 12:59 UTC
Labels: bug

**Comment by cchgray** [comment] 2023-04-08 13:14
I have this problem with 0.82 on my wireless mac keyboard. Weirdly, the arrows move the bevel's screen position. When i changed the hotkey back to default the arrows are working again to cycle.
