### ISSUE TITLE
In Dark mode, it's not possible to see the currently entered keyboard shortcut in the preference pane

### ISSUE THREAD

**Issue by matthewmayer** [snark/jumpcut#23] opened 2019-09-17 03:59 UTC
Light mode:
<img width="640" alt="Screenshot 2019-09-17 at 10 58 08" src="https://user-images.githubusercontent.com/152770/65010465-2397eb00-d93a-11e9-8e36-b0e332505721.png">

Dark mode:
<img width="642" alt="Screenshot 2019-09-17 at 10 58 13" src="https://user-images.githubusercontent.com/152770/65010472-272b7200-d93a-11e9-9c3d-7c52d604d03b.png">

**Comment by snark** [comment] 2019-09-17 16:20
Duplicate of #15 -- Matthew, there's a fix in the master branch and a new bugfix release that will include it, coming as soon as later this week.

**Closed by snark** 2019-09-17 16:20 UTC
