### ISSUE TITLE
Bezel doesn't appear after second monitor is removed

### ISSUE THREAD

**Issue by salmeenm** [snark/jumpcut#76] opened 2022-05-05 16:50 UTC
Hey there! I use Jumpcut all the time on my Mac (using Big Sur version 11.6.1) for work, but suddenly (I have Version 0.80 of Jumpcut), the bezel where I can cycle through my pasted text and actually see what I've copied has disappeared. I can still cycle through blindly, and it will paste text wherever I stop cycling. Any tips on how to remedy this, so I can see the bezel again? Thanks!
![Jumpcut preferences](https://user-images.githubusercontent.com/105007844/166973012-ea2814cd-62c6-4eae-8db3-147411f1823c.png)

**Comment by snark** [comment] 2022-05-05 20:44
QQ for you, @salmeenm -- are you on a making use of multiple desktops via Mission Control? Or are you on a dual screen setup? I'm on 11.6.5 and can confirm that the bezel shows up as expected, so it shouldn't be a Big Sur problem, but there are some regressions involving those two scenarios that might cause something like what you're describing. (The multi-desktop issue will be resolved in an imminent bugfix release; the dual screen problem will take slightly longer.)

If it's neither of those, we can dig in more deeply.

**Comment by salmeenm** [comment] 2022-05-05 20:47
I am on a dual screen set up. I just noticed it works fine when I was working on my laptop, but when I was plugged into my second monitor, this issue cropped up.

**Comment by snark** [comment] 2022-05-05 20:50
My *guess* would be that it's displaying the bezel on the wrong screen, which is obviously a bug but hopefully a little more useful until it gets fixed than just not displaying at all.

**Comment by salmeenm** [comment] 2022-05-05 20:56
I just plugged my laptop back into my second monitor, and now it's working fine.😅  Thank you for your assistance! When I couldn't use Jumpcut, it really threw a wrench into my workflow - it's too good!

**Comment by snark** [comment] 2022-05-05 20:58
Yeah, that's a bug -- it doesn't adjust for which screen you're using, so it's trying to display on the second monitor even when it's been removed. I don't have a second monitor, so this is something I've never noticed, but I'll get it resolved ASAP, because it (and issue #54 which is the same root cause) sounds pretty frustrating. I may reach out to see if you can confirm the fix when it's written; thanks for the bug report!

**Comment by snark** [comment] 2022-05-05 20:59
(This is awful workflow, but if you remove the second display, quitting and relaunching Jumpcut should get the bezel back where it belongs.)

**Comment by salmeenm** [comment] 2022-05-05 21:05
Thank you so much! I'd be happy to help confirm a fix whenever needed.

**Comment by snark** [comment] 2022-05-10 11:57
@salmeenm I have an experimental build that hopefully is going to fix this problem, but I can't test since I don't have a dual-monitor setup. Shoot me an email at the contact listed in my GitHub profile if you want to try it out!

**Comment by snark** [comment] 2022-05-25 11:45
Now released in 0.82, with Sparkle updates arriving shortly. Thanks for your patience, everyone! And big thanks to @salmeenm for testing the fix.

**Closed by snark** 2022-05-25 11:45 UTC
Labels: bug
