### ISSUE TITLE
"Clipping selection pastes" not working in 0.7 beta2

### ISSUE THREAD

**Issue by seren** [snark/jumpcut#14] opened 2019-08-21 21:32 UTC
Using the hotkey (opt-ctl-v in my case) will cycle through the clippings, however I need to the manually paste to get the selected clipping, even with the "Clipping selection pastes" option checked.

OS: 10.14.6
Jumpcut: 0.7 beta 2 (2019082101)

**Comment by zepgurl** [comment] 2019-08-21 21:48
I find the same.  But this was my initial problem with the last build.  It worked great all the way up to Mojave.  Then something happened with Mojave and Jumpcut no longer pasted.

**Comment by snark** [comment] 2019-08-21 23:40
@seren @zepgurl On a naive computer, when you launch Jumpcut you should get a prompt informing you that you need to add Jumpcut to the Accessibility panel in Security ("Grant access to this application in Security & Privacy preferences, located in System Preferences"); if you do so, it'll add Jumpcut to the list of applications *but not check the check box*. (Awesome UX from Apple.) This needs to happen, and the need for it is non-obvious.

If that's what's happening, you should see a message in Jumpcut's general preference: "To activate pasting, in the "Security & Privacy" System Preference, in the "Privacy" tab, go to "Accessibility" and check Jumpcut. (Click the "+" if Jumpcut is not listed.)" This message goes away if Jumpcut has the Accessibility privileges it needs. Do you see this message? Is Jumpcut listed in the list of applications, and is the checkbox checked? If you *don't* see the message, Jumpcut *is* present in the list of applications, and the checkbox *is* checked, that's a biggish problem.

I myself am on High Sierra, but I can confirm that my wife's computer (running Mojave, 10.14.6) the "clipping selection pastes" function works successfully. (Thinking back, at one point she may have had to delete a previous Jumpcut entry in "System Preferences > Privacy > Accessibility" then re-add it, but I think that was the result of an experimental build which didn't work.)

If this in fact is the problem, I'm happy to take feedback on how to make this instruction more clear/visible, although due to the time constraints from the Catalina release better UX may need to wait for 0.7.1.

**Comment by capndesign** [comment] 2019-08-21 23:55
For a data point, 0.7.1b2 _does_ auto-paste with the hotkey for me. (I have the accessibility bit flipped.)

**Comment by bunk3m** [comment] 2019-08-22 00:07
Just a note about my installation which went well on macOS 10.14.6.  Thanks @snark!

Quit the old 0.63 version.  Drag & drop the new version 0.7b2 into the Applications folder.

Right click on the new application and open from the pop-up menu.

Set the preferences again.

Checked the Security Privacy Accessibility window and see that Jumpcut is already enabled.  Cool!

So far working like a charm.  I'm excited to test the copy password and see what happens.

One question.
Are there preferences etc. from 0.63 that I should manually erase?

**Comment by danielcompton** [comment] 2019-08-22 01:24
After updating to 0.7.0-beta2 I needed to remove and then re-add the Jumpcut entry to Accessibility before pasting when cycling worked.

**Comment by snark** [comment] 2019-08-22 02:07
Thanks, @danielcompton -- did you happen to see whether the warning message displayed in the Jumpcut preferences? This seems like some sort of weird edge case caused by the update.

**Comment by snark** [comment] 2019-08-22 02:08
@bunk3m No, any unused preferences for 0.63 should be harmless. (I want to tweak appearance and make a few minor functional changes, but as I noted elsewhere, getting a 64-bit version out before the Catalina release is a higher priority.)

**Comment by bunk3m** [comment] 2019-08-22 02:19
One item I noticed but not sure has been reported.

The App icon is the Mac default not the scissors.

New app on the left, old on the right.
<img width="529" alt="Screen Shot 2019-08-21 at 22 18 36" src="https://user-images.githubusercontent.com/3494567/63480893-ae7fe580-c461-11e9-9aea-67b60c6254d5.png">

**Comment by snark** [comment] 2019-08-22 03:03
@bunk3m Waiting to see if my friend the designer has a chance to make a cleaner icon before the release. Fingers crossed! If not, we'll use the old one one more time.

**Comment by danielcompton** [comment] 2019-08-22 05:20
> did you happen to see whether the warning message displayed in the Jumpcut preferences?

I checked in all three tabs and didn’t see anything, which one would I have looked in? I had previously added Jumpcut to Accessibility and checked it, so possibly it was detecting that and not showing the message?

**Comment by snark** [comment] 2019-08-22 12:40
Thanks, @danielcompton -- that's helpful. The message displays in the "General" tab (you can see what it looks like by removing Jumpcut from Accessibility), so it sounds like whatever upgrade-related problem that causes this isn't something that I can easily detect. I'll see how easy it is to add a one-time alert to upgraders.

**Comment by seren** [comment] 2019-08-22 17:38
Ahh, thanks for the tip @snark. I think my problem was that I renamed the old version of Jumpcut and started running the beta. My Accessibility list showed "Jumpcut" in the list and checked, however it may have been referencing the old version. Removing and re-adding it to the accessibility list solved the problem.

In case you're curious, I was able to reproduce the issue by:
- Deleting JC from the accessibility list
- Re-adding the old version
- Tested that it could paste
- Launch the new version (with no warning and no message in the JC preferences)
- Find that paste doesn't work

**Comment by zepgurl** [comment] 2019-08-22 19:53
I ditto what @seren discovered.  I copied the same steps and find Jumpcut is working like a breeze.  🙂

**Comment by snark** [comment] 2019-08-23 02:19
Okay, upgraders are going to see the following message, the first (and only the first) time they run:

Users upgrading from older versions of Jumpcut may need to remove Jumpcut from the Security & Privacy Preference's Accessibility tab and add it again manually in order to fix the "Clipping Selection Pastes" option. This should be a one-time fix.

Hopefully that helps people who have the same issue; thanks for everyone's feedback.

**Closed by snark** 2019-08-23 02:19 UTC
