### ISSUE TITLE
0.70 and 0.71 crashing

### ISSUE THREAD

**Issue by SusumuKusa** [snark/jumpcut#30] opened 2019-10-16 04:37 UTC
Created a GitHub account to post this, as I've used Jumpcut day in, day out for over a decade now; it's an invaluable time-saver. Thanks so much for creating it Steve.

Sadly both version 0.70 and 0.71 are crashing for me, shortly after the application is started automatically at login. Even if I don't touch Jumpcut, it will stop running a short while after login.

Attaching a crash log here, and would greatly appreciate any help anybody can give.

[Jumpcut_2019-10-16-130014_SK-MacBook-Pro.pdf](https://github.com/snark/jumpcut/files/3732445/Jumpcut_2019-10-16-130014_SK-MacBook-Pro.pdf)

**Comment by snark** [comment] 2019-10-16 21:42
@SusumuKusa It looks like it's triggering on `keyboardInputSourceChanged` -- any chance you're switching keyboard types, e.g. between US and another language, or between QWERTY and Dvorak?

**Comment by snark** [comment] 2019-10-17 13:14
Thanks, @SusumuKusa -- there's code in the 0.7x branch that replaces a method in ShortcutRecord (v1), as used in 0.63, that wasn't brought over to ShortcutRecorder 2; I did test it but not particularly thoroughly, so I'll dig in and see what I can figure out.

**Comment by SusumuKusa** [comment] 2019-10-18 10:33
Thanks Steve.

In the meantime I'm running 0.63 just fine; would be lost without your little utility after all these years using it.

**Comment by snark** [comment] 2019-11-07 20:54
@SusumuKusa I've reproduced this, although I don't use Katakana myself. It seems to be specific (probably non-Roman?) keyboards that trigger the crash, as switching between US English, Dvorak, Greek, and German layout all work successfully under 0.71.

This is currently my highest-priority bug fix for the next release.

**Comment by snark** [comment] 2019-11-10 02:22
@SusumuKusa I believe I have a fix -- would you contact me in the email listed in my profile for testing purpose?

**Comment by SusumuKusa** [comment] 2019-11-18 04:18
Apologies for the delayed response Steve, have just emailed you.

**Comment by snark** [comment] 2019-12-10 18:17
(Update for anyone who stumbles across this via Google or the like--@SusumuKusa has tested and confirmed that the fix currently in master works, and it will be included in the next release, which shouldn't be too far off in the future.)

**Comment by snark** [comment] 2020-02-21 01:41
@SusumuKusa 0.72 is released; I'll push out a Sparkle appcast change and update the brew cask shortly. Want to try downloading it from the releases page and see if it fixes your issues?

**Comment by snark** [comment] 2020-02-23 17:09
@SusumuKusa I'm closing per feedback in #38 than 0.72 resolved this issue, but if Katakana is behaving differently than Pinyin for some reason, please reopen the issue or file a new one. Thanks so much for the bug report!

**Closed by snark** 2020-02-23 17:09 UTC
Labels: bug, high-priority
