### ISSUE TITLE
Installing from preferences -> check now failed, brew cast install works

### ISSUE THREAD

**Issue by lderezinski** [snark/jumpcut#18] opened 2019-09-04 11:48 UTC
I was unable to get the install from jumpcut->preferences->check now.  The upgrade screen came up and it appeared to start to download, but then would fail.  It's possible that the download site is just overwhelmed.  

I am running: OS X 10.14.6, Homebrew 2.1.11

But what did work for me is to delete the file:
/Applications/Jumpcut.app

Then use brew like so:

    > $ sudo rm -rf /Applications/Jumpcut.app                            
                                                                                
    > $ brew cask install jumpcut                                        
    ==> Satisfying dependencies
    ==> Downloading https://github.com/snark/jumpcut/releases/download/v0.70/Jumpcut
    Already downloaded: /Users/linda/Library/Caches/Homebrew/downloads/7f6a0397c87aa2202c6710738685c5ffeff439f7430b4bb79118963c7be33390--Jumpcut-0.70.tar.bz2
    ==> Verifying SHA-256 checksum for Cask 'jumpcut'.
    ==> Installing Cask jumpcut
    ==> Moving App 'Jumpcut.app' to '/Applications/Jumpcut.app'.
    🍺  jumpcut was successfully installed!

**Comment by snark** [comment] 2019-09-04 12:13
@lderezinski I confirmed this; thanks for the report. I'm not sure if the problem is Sparkle, or how I signed the app. (Sparkle's behavior has changed a lot since 2008.) Unless using a .tgz file instead of a .tar.bz2 file makes a difference, I don't think there's anything I can do, because the problem is in the 10-year-old code.

However, I should put a note up in the Sparkle app cast suggesting users download it manually or view `brew`.

**Comment by lderezinski** [comment] 2019-09-04 12:20
I forgot to give the last step.  As other folks have said,  after you upgrade the app go to:

     System preferences->Security & Privacy -> Privacy -> Accessibility.

Then delete jumpcut from the list, then re-add.  Life is good!

@snark I am so happy and thankful you took the time to upgrade it.  This saves me time daily.

**Comment by snark** [comment] 2019-09-27 01:53
Folks, I'm going to close this out; it's clearly an issue but I don't think I can solve it with code, just with documentation. Thanks for filing the issue and your feedback!

**Closed by snark** 2019-09-27 01:53 UTC
