### ISSUE TITLE
Jumpes back to Previous Desktop/Workspace Instead of Pasting

### ISSUE THREAD

**Issue by betweendrafts** [snark/jumpcut#69] opened 2022-04-30 18:04 UTC
When I switch to a different desktop/workspace on MacOS 12.3.1 (iMac 5K 27' Late 2015), v0.80 (default configuration) does not show the clipboard content or paste from it, but jumps back instead to the desktop/workspace I’d previously used.

**Comment by snark** [comment] 2022-04-30 18:34
Dupe of issue #67 -- thanks for the bug report, and there will be a fix released next week.

**Closed by snark** 2022-04-30 18:34 UTC
